{% set name = "pytao" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 11d2f6940b2103f0aeee719d79bf99d236fc3a3ebda20fd78e3c3515c7412d45

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools_scm
  run:
    - python >=3.9
    - bmad >=20240809
    - h5py
    - matplotlib-base
    - numpy
    - pexpect
    - pydantic >=2

test:
  requires:
    - git
    - pytest
    - pytest-cov
    - bokeh
    - ipython
    - openpmd-beamphysics
  imports:
    - pytao
    - pytao.plotting
    - pytao.plotting.bokeh
  commands:
    # Add back once https://github.com/bmad-sim/pytao/issues/101 is resolved:
    # - pytao --help
    - test -f $PREFIX/bin/pytao-gui  # [unix]
    - git clone --depth 1 https://github.com/bmad-sim/bmad-ecosystem bmad
    - echo | pytao -lat $PWD/bmad/bmad-doc/tao_examples/erl/lat.bmad
    - TAO_REUSE_SUBPROCESS=1 ACC_ROOT_DIR=$PWD/bmad pytest -v --pyargs pytao.tests

about:
  home: https://github.com/bmad-sim/pytao
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: PyTao is wrapper on top of Tao and allow users to access the Tao library via ctypes or pexpect.
  description: |
    PyTao is wrapper on top of Tao and allow users to access the Tao library via ctypes or pexpect.
    Tao is an open source general purpose program for charged particle and X-ray simulations in 
    accelerators and storage rings.
  doc_url: https://bmad-sim.github.io/pytao
  dev_url: https://github.com/bmad-sim/pytao

extra:
  recipe-maintainers:
    - hhslepicka
    - ChristopherMayes
    - ken-lauer
