{% set name = "pytao" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bmad-sim/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 432e88deb53cb448daa6f6fa406394984084d42ccf625beece9eccbe3b9010f8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - h5py
    - numpy
    - pexpect

test:
  imports:
    - pytao

about:
  home: https://github.com/bmad-sim/pytao
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: PyTao is wrapper on top of Tao and allow users to access the Tao library via ctypes or pexpect.
  description: |
    PyTao is wrapper on top of Tao and allow users to access the Tao library via ctypes or pexpect.
    Tao is an open source general purpose program for charged particle and X-ray simulations in 
    accelerators and storage rings.
  doc_url: hhttps://bmad-sim.github.io/pytao
  dev_url: hhttps://github.com/bmad-sim/pytao

extra:
  recipe-maintainers:
    - hhslepicka
    - ChristopherMayes
